# Generated by Django 4.1.6 on 2023-02-10 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab1p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField(blank=True)),
                ('review', models.TextField(blank=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab1p.book')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, to='lab1p.book'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserBook',
        ),
        migrations.AddField(
            model_name='userprofilebook',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lab1p.userprofile'),
        ),
    ]
