# Generated by Django 4.1.6 on 2023-02-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0002_userprofilebook_userprofile_bio_userprofile_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, to='lab1p.book'),
        ),
    ]
