# Generated by Django 4.1.6 on 2023-02-10 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab1p', '0003_alter_userprofile_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Name',
            field=models.CharField(default='To read', max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='userAdded',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab1p.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('creator', 'Name')},
        ),
    ]
