# Generated by Django 4.1.6 on 2023-02-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0004_collection_creator_alter_collection_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='userAdded',
            new_name='users',
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('users', 'Name')},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='creator',
        ),
    ]
