# Generated by Django 4.1.6 on 2023-02-10 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lab1p', '0006_alter_collection_unique_together_collection_creator_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('creator', 'Name')},
        ),
    ]
