# Generated by Django 4.1.6 on 2023-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0009_alter_collection_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='Information',
            field=models.CharField(default='', max_length=150),
        ),
    ]
