# Generated by Django 4.1.6 on 2023-02-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0013_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookgenre',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookgenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='userprofilebook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='userprofilebook',
            name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookGenre',
        ),
        migrations.DeleteModel(
            name='UserProfileBook',
        ),
    ]
