# Generated by Django 4.1.6 on 2023-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0014_remove_bookgenre_book_remove_bookgenre_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(to='lab1p.collection'),
        ),
    ]
