# Generated by Django 4.1.6 on 2023-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0015_remove_collection_book_book_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(blank=True, to='lab1p.collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='Information',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
