# Generated by Django 4.1.6 on 2023-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0016_alter_book_collections_alter_collection_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='lab1p.genre'),
        ),
    ]
