# Generated by Django 4.1.6 on 2023-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0018_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Bio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
