# Generated by Django 4.1.6 on 2023-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0019_author_bio_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Bio',
            field=models.CharField(blank=True, default='No bio', max_length=200),
        ),
    ]
