# Generated by Django 4.1.6 on 2023-02-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0021_alter_book_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='collections',
        ),
        migrations.AddField(
            model_name='book',
            name='collections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_for_collecton', to='lab1p.collection'),
        ),
    ]
