# Generated by Django 4.1.6 on 2023-02-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0022_remove_book_collections_book_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='collections',
        ),
        migrations.AddField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='books_for_collecton', to='lab1p.collection'),
        ),
    ]
