# Generated by Django 4.1.6 on 2023-02-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0023_remove_book_collections_book_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='books', to='lab1p.genre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='profile_f_books', to='lab1p.book'),
        ),
    ]
