# Generated by Django 4.1.6 on 2023-02-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1p', '0024_alter_book_genre_alter_userprofile_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='lab1p.genre'),
        ),
    ]
